/* =================================================
   CTFs & LABS — central data source
   Add new entries here. index.html shows latest 3.
   labs.html shows all.

   HOW TO ADD A NEW LAB:
   Copy the template block, fill it in,
   add at the TOP (newest first).
   ================================================= */
const labs = [
  {
    id: 'tcm-malware',
    name: 'Practical Malware Analysis & Triage',
    platform: 'TCM Security',
    icon: 'fa-bug',
    diff: 'hard',
    date: 'In Progress',
    status: 'active',
    color: '#c084fc',
    bg: 'rgba(168,85,247,0.1)',
    border: 'rgba(168,85,247,0.25)',
    summary: 'Static & dynamic malware analysis. PE structure, x32dbg debugging, Ghidra RE, YARA rule writing. Learning to triage a sample end-to-end.',
    tags: ['x32dbg', 'Ghidra', 'YARA', 'PE Analysis', 'Sandboxing'],
    url: 'now.html',
  },
  {
    id: 'htb-cdsa',
    name: 'CDSA Certification',
    platform: 'Hack The Box',
    icon: 'fa-shield-halved',
    diff: 'medium',
    date: 'March 2026',
    status: 'done',
    color: '#9fef00',
    bg: 'rgba(159,239,0,0.08)',
    border: 'rgba(159,239,0,0.25)',
    summary: 'Certified Defense Security Analyst. Covered SOC operations, threat hunting, alert triage, and incident response across real-world scenarios.',
    tags: ['SOC', 'Threat Hunting', 'IR', 'SIEM'],
    url: '',
  },
  {
    id: 'tryhackme-soc',
    name: 'SOC Analyst Path',
    platform: 'TryHackMe',
    icon: 'fa-route',
    diff: 'medium',
    date: 'February 2026',
    status: 'done',
    color: '#88cc14',
    bg: 'rgba(136,204,20,0.08)',
    border: 'rgba(136,204,20,0.25)',
    summary: 'Comprehensive SOC analyst learning path covering log analysis, SIEM, phishing investigation, and endpoint forensics.',
    tags: ['SIEM', 'Log Analysis', 'Phishing', 'Forensics'],
    url: '',
  },
  {
    id: 'btlo-phishing',
    name: 'Phishing Email Investigation',
    platform: 'Blue Team Labs',
    icon: 'fa-envelope-open',
    diff: 'medium',
    date: 'January 2026',
    status: 'done',
    color: '#3b82f6',
    bg: 'rgba(59,130,246,0.08)',
    border: 'rgba(59,130,246,0.25)',
    summary: 'Investigated a multi-stage phishing campaign. Header analysis, URL detonation, IOC extraction, and full incident timeline.',
    tags: ['Email Forensics', 'Headers', 'IOCs', 'SPF/DKIM'],
    url: '',
  },
  {
    id: 'cyberdef-sysmon',
    name: 'Sysmon Threat Hunting',
    platform: 'CyberDefenders',
    icon: 'fa-magnifying-glass',
    diff: 'medium',
    date: 'December 2025',
    status: 'done',
    color: '#06b6d4',
    bg: 'rgba(6,182,212,0.08)',
    border: 'rgba(6,182,212,0.25)',
    summary: 'Used Sysmon telemetry to hunt for lateral movement and credential access. Identified LSASS dump and pass-the-hash attack chain.',
    tags: ['Sysmon', 'Lateral Movement', 'Credential Access', 'EVTX'],
    url: '',
  },
  {
    id: 'tryhackme-ad',
    name: 'Active Directory Attacks',
    platform: 'TryHackMe',
    icon: 'fa-network-wired',
    diff: 'hard',
    date: 'November 2025',
    status: 'done',
    color: '#88cc14',
    bg: 'rgba(136,204,20,0.08)',
    border: 'rgba(136,204,20,0.25)',
    summary: 'Kerberoasting, AS-REP roasting, DCSync, BloodHound enumeration. Defender perspective: learned how each technique appears in logs.',
    tags: ['Kerberos', 'BloodHound', 'DCSync', 'AD'],
    url: '',
  },
  {
    id: 'cyberdef-volatility',
    name: 'Memory Forensics — Volatility',
    platform: 'CyberDefenders',
    icon: 'fa-microchip',
    diff: 'hard',
    date: 'October 2025',
    status: 'done',
    color: '#06b6d4',
    bg: 'rgba(6,182,212,0.08)',
    border: 'rgba(6,182,212,0.25)',
    summary: 'Memory dump analysis with Volatility. Extracted running processes, network connections, and injected shellcode from a compromised Windows image.',
    tags: ['Volatility', 'Memory Forensics', 'Process Injection', 'DFIR'],
    url: '',
  },
  {
    id: 'tryhackme-jrpent',
    name: 'Junior Penetration Tester',
    platform: 'TryHackMe',
    icon: 'fa-user-ninja',
    diff: 'medium',
    date: 'September 2025',
    status: 'done',
    color: '#88cc14',
    bg: 'rgba(136,204,20,0.08)',
    border: 'rgba(136,204,20,0.25)',
    summary: 'Full Jr PenTester path. Web app attacks, privilege escalation, network exploitation. Helps me understand attacker perspective for better detection logic.',
    tags: ['Web App', 'PrivEsc', 'Exploitation', 'Recon'],
    url: '',
  },
  /* ── Add new labs above this line ───────────────────────────────────────
  {
    id: 'your-lab-id',
    name: 'Lab Name',
    platform: 'Platform Name',
    icon: 'fa-shield-halved',
    diff: 'medium',          // 'easy' | 'medium' | 'hard' | 'insane'
    date: 'May 2026',
    status: 'done',          // 'done' | 'active'
    color: '#00ffe5',
    bg: 'rgba(0,255,229,0.08)',
    border: 'rgba(0,255,229,0.25)',
    summary: 'One or two sentences about what you learned.',
    tags: ['Tag1', 'Tag2'],
    url: '',                 // optional link to writeup
  },
  ─────────────────────────────────────────────────────────────────────── */
];
